on:
  workflow_call:
    inputs:
      mod-path:
        required: false
        default: "./go.mod"
        type: string
        description: "Path to the go.mod file, by default it is assumed to be in the root of the repository"
      test-path:
        required: false
        default: "./..."
        type: string
        description: "Path to the tests to run, by default all tests are run"
      test-count:
        required: false
        default: 10
        type: number
        description: "Number of times to run each test"
      enable-correctness:
        required: false
        default: true
        type: boolean
        description: "Enable correctness tests"
      enable-performance:
        required: false
        default: true
        type: boolean
        description: "Enable performance tests"
      enable-fuzz:
        required: false
        default: true
        type: boolean
        description: "Enable fuzz tests"
      retention-days:
        required: false
        default: 2
        type: number
        description: "Number of days to keep the test results in the artifact store"

jobs:
  test-small-correctness:
    name: Small Tests - Correctness
    runs-on: ubuntu-latest
    if: ${{ inputs.enable-correctness }}
    steps:

    - name: Checkout code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.mod-path }}

    - name: Get dependencies
      run: go mod download && go install gotest.tools/gotestsum@latest

    - name: Correctness tests
      run: gotestsum --packages=${{ inputs.test-path }} --junitfile="./correctness-tests.xml" -- -coverprofile="./correctness-tests-coverage.out" -count=${{ inputs.test-count }} -race

    - name: Store test reports
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: Test small reports
        path: |
          ./correctness-tests.xml
          ./correctness-tests-coverage.out
        if-no-files-found: ignore
        retention-days: ${{ inputs.retention-days }}

  test-small-performance:
    name: Small Tests - Performance
    runs-on: ubuntu-latest
    if: ${{ inputs.enable-performance }}
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.mod-path }}

    - name: Get dependencies
      run: go mod download

    # TODO Add test for on PR, run performance test on HEAD and PR, and check diff
    - name: Performance tests
      run: go test -bench="." -count=${{ inputs.test-count }} ${{ inputs.test-path }} > ./performance-tests.txt

    - name: Store test reports
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: Test small reports
        path: ./performance-tests.txt
        if-no-files-found: ignore
        retention-days: ${{ inputs.retention-days }}

  test-small-fuzz:
    name: Small Tests - Fuzz
    runs-on: ubuntu-latest
    if: ${{ inputs.enable-fuzz }}
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ inputs.mod-path }}

    - name: Get dependencies
      run: go mod download

    - name: Fuzz tests
      run: find . -maxdepth 3 -type d \( ! -name . \) -not -path "./.git/*" -exec bash -c "cd '{}' && go test --fuzz=. --fuzztime=10s"
